create schema if not exists private;

revoke all on schema private from public, anon, authenticated;

create table private.allowed_users (
  email text primary key check (email = lower(email)),
  created_at timestamptz not null default now()
);

insert into private.allowed_users (email)
values ('anilgupta.eyecentre@gmail.com')
on conflict (email) do nothing;

create or replace function public.is_shop_user()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from private.allowed_users
    where email = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

revoke all on function public.is_shop_user() from public, anon;
grant execute on function public.is_shop_user() to authenticated;

create table public.optical_records (
  id bigint generated by default as identity primary key,
  record_number text generated always as ('ECO-' || lpad(id::text, 4, '0')) stored unique,
  owner_id uuid not null default auth.uid() references auth.users(id) on delete restrict,
  full_name text not null check (length(trim(full_name)) > 0),
  age smallint check (age is null or age between 0 and 120),
  sex text check (sex is null or sex in ('Male', 'Female', 'Other')),
  phone text check (phone is null or phone ~ '^[0-9]*$'),
  address text not null check (length(trim(address)) > 0),
  complaints text,
  prescription jsonb not null default '{}'::jsonb,
  order_details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index optical_records_owner_id_idx on public.optical_records(owner_id);
create index optical_records_full_name_lower_idx on public.optical_records(lower(full_name));
create index optical_records_phone_idx on public.optical_records(phone);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger optical_records_set_updated_at
before update on public.optical_records
for each row execute function public.set_updated_at();

alter table public.optical_records enable row level security;

create policy "authorized users select own records"
on public.optical_records for select to authenticated
using (public.is_shop_user() and owner_id = auth.uid());

create policy "authorized users insert own records"
on public.optical_records for insert to authenticated
with check (public.is_shop_user() and owner_id = auth.uid());

create policy "authorized users update own records"
on public.optical_records for update to authenticated
using (public.is_shop_user() and owner_id = auth.uid())
with check (public.is_shop_user() and owner_id = auth.uid());

create policy "authorized users delete own records"
on public.optical_records for delete to authenticated
using (public.is_shop_user() and owner_id = auth.uid());

revoke all on table public.optical_records from anon;
grant select, insert, update, delete on table public.optical_records to authenticated;
grant usage, select on sequence public.optical_records_id_seq to authenticated;
